### ISSUE TITLE
Can't resolve jsx files during build

### ISSUE THREAD

**Issue by rawbeans** [transitive-bullshit/create-react-library#218]
I am getting the following error trying to build my library. 
```
Error: Could not resolve './MyComponent' from src/components/index.js
```

It only consists of a single component defined in `src/components/MyComponent.jsx`

Here is the contents of `src/components/index.js`:
```
export { default as MyComponent } from './MyComponent';
```

How do I configure `microbundle-crl` to resolve jsx files? I see that the `node-resolve` plugin is a dependency, so it should be possible.

**Comment by antondelorme** [comment]
Hey @rawbeans, I am myself trying to figure out why microbundle can't seem to resolve .jsx automagically. Though the workaround atm is just adding the .jsx manually.
` export { default as MyComponent } from './MyComponent.jsx';

Slightly annoying, but its only in the index files anyway so I'm not too affected by it. 

Still, though, I'm interested if anyone knows why the path is not being resolved. I've looked quite a bit here in CRL but I'm thinking its in how microbundle is configuring Rollup

**Comment by transitive-bullshit** [comment]
If you update `microbundle-crl` to `0.13.9` this should be fixed by this upstream fix here https://github.com/developit/microbundle/pull/571

**Comment by transitive-bullshit** [comment]
Closing as resolved; feel free to re-open if you're still having issues.

**Comment by shubhamkes** [comment]
Having same issue 
```json
"microbundle-crl": "^0.13.10"
```

In my case I am importing a .ts file, but it doesnt seem to resolve without adding .ts
